baseURL = "https://huntermatthews.github.io/"
title = "Hunter Matthews"
languageCode = "en-us"
 
# updates: git submodule update --remote themes/devise
# hugo new content content/posts/my-first-post.md
# hugo server --buildDrafts

theme = "devise"     
relativeURLs = true
enableEmoji = true
#googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, Hunter Matthews"


# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -500
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -100
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    title = "Resume"
    url = "/resume/hunter-matthews-resume.pdf"
    weight = -400


# Configuration Features
[params]
  description = "Hunter Matthews tiny corner of the internets"      # Your meta description of the site
  header_title = "Hunter Matthews"                                  # Your header title
  header_subtitle = "The haus that unix built...."                  # Your header subtitle
  home_image = "/images/clint-avatar.jpg"                                 # Path to header image starting from the static directory
  recent_posts = 5                                                  # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]                          # Main sections to include in recent posts

  [[params.style]]                                                  # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"

  [[params.social]]
    fa_icon = "fab fa-github fa-1x"                # Font Awesome icon class
    href = "http://github.com/huntermatthews"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/comm/in/hunter-matthews-b7363b11"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "mailto:blog@unix.haus"
#  [[params.social]]
#    fa_icon = "fab fa-twitter fa-1x"
#    href = ""




# themse
#
# devise - started with, SIMPLE
#
# Anatole - two column, simple(ish)
#
# Coder - simple, stark two color
#
# Console - simpish, ascii art based
#
# type - simple?? and I really like this one 
#
#